// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 文件节点表
type File struct {
	FileID      uint64    `gorm:"column:file_id;AUTO_INCREMENT;NOT NULL"`                // 文件id
	FileName    string    `gorm:"column:file_name;NOT NULL"`                             // 文件名称
	FileContent string    `gorm:"column:file_content;NOT NULL"`                          // 文件内容,最大64k
	CosKey      string    `gorm:"column:cos_key;NOT NULL"`                               // 文件在cos中的key
	CreateTime  time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;NOT NULL"` // 创建时间
	UpdateTime  time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;NOT NULL"` // 更新时间
}

func (m *File) TableName() string {
	return "file"
}
