// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 节点表
type Node struct {
	NodeID     uint64    `gorm:"column:node_id;primary_key;AUTO_INCREMENT"`             // 节点id
	NodeType   uint      `gorm:"column:node_type;NOT NULL"`                             // 节点类型
	Name       string    `gorm:"column:name;NOT NULL"`                                  // 文件名称
	Content    string    `gorm:"column:content;NOT NULL"`                               // 文件内容,最大64k
	CosKey     string    `gorm:"column:cos_key;NOT NULL"`                               // 文件在cos中的key
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;NOT NULL"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;NOT NULL"` // 更新时间
}

func (m *Node) TableName() string {
	return "node"
}

