// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 搜索索引表
type SearchIndex struct {
	ID         uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT"`                  // 索引id
	Keyword    string    `gorm:"column:keyword;NOT NULL"`                               // 关键词,加密后的
	FileID     uint64    `gorm:"column:file_id;NOT NULL"`                               // 文件id
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;NOT NULL"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;NOT NULL"` // 更新时间
}

func (m *SearchIndex) TableName() string {
	return "search_index"
}

