// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 解密密钥表
type SecretKey struct {
	ID         uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT"`                  // 主键id
	UserID     uint64    `gorm:"column:user_id;NOT NULL"`                               // 用户id
	FileID     uint64    `gorm:"column:file_id;NOT NULL"`                               // 文件id
	Key        string    `gorm:"column:key;NOT NULL"`                                   // 解密密钥,已加密
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;NOT NULL"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;NOT NULL"` // 更新时间
}

func (m *SecretKey) TableName() string {
	return "secret_key"
}

